### PR TITLE
Fix crash with Aqara Lock

### PR DESCRIPTION
**Pull request by dzungpv**
Fix bug here Koenkk/zigbee2mqtt#349

### CODE REVIEW

**Comment by dzungpv** [comment]
I only add those but Atom reformat the code:
```
        var deviceId = zclId.device(260, 10).key;
        // special xiaomi struct-string
        if (attrId === 65281&&deviceId!=='doorLock') {
            ru['xiaoMiStruct'](name)(this);
        } 
```

**Comment by Koenkk** [comment]
I see, can you readd the spaces? As this can make future merging more difficult. After that I can merge it.

**Comment by dzungpv** [comment]
@Koenkk I don't understand what you mean. That function for Xiaomi device right? But it crash with xiaomi aqara lock, i just ignore the function with the 'doorlock' and it not crash anymore, all other device will not affect by this PR. It is the 'struct' data inside the 'xiaoMiStruct' and still not decode. And it make zigbe2mqtt crash. I see the structure in the curtain too but it not cause the crash.

**Comment by dzungpv** [comment]
If you mean some change about spaces in code. Just rewrite my commit with the code i post above. I never code in nodejs/javascript except for zigbee2mqtt and i not know much about Lint format/setup

**Comment by Koenkk** [comment]
done! thanks!

**Pull request merged**
